"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

SECURITY ENHANCEMENTS:
This settings file implements security best practices to protect against:
- Cross-Site Scripting (XSS)
- Cross-Site Request Forgery (CSRF)
- SQL Injection
- Clickjacking
- Man-in-the-Middle attacks
- Session hijacking

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO: In production, load from environment variable
SECRET_KEY = 'django-insecure-f_k_i)d89r!95w$ow3hwfz$o#wk5j*%tcjve#jxa=ae*7_5$$_'

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production
DEBUG = True

# In production, set this to your actual domain names
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Enforce minimum 8 characters for stronger passwords
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Authentication redirect URLs
LOGIN_URL = '/relationship/login/'
LOGIN_REDIRECT_URL = '/relationship/books/'
LOGOUT_REDIRECT_URL = '/relationship/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =====================================================
# SECURITY SETTINGS
# =====================================================

# 1. HTTPS and SSL Settings
# --------------------------
# Force HTTPS in production (redirects all HTTP to HTTPS)
# Set to True when deploying with HTTPS
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS

# Ensure cookies are only sent over HTTPS
# Protects against man-in-the-middle attacks
# Enable these in production with HTTPS
SESSION_COOKIE_SECURE = False  # Set to True in production
CSRF_COOKIE_SECURE = False     # Set to True in production

# HTTP Strict Transport Security (HSTS)
# Forces browsers to use HTTPS for specified duration
# Only enable in production with HTTPS
SECURE_HSTS_SECONDS = 0  # Set to 31536000 (1 year) in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Set to True in production
SECURE_HSTS_PRELOAD = False  # Set to True in production


# 2. Cross-Site Scripting (XSS) Protection
# -----------------------------------------
# Enable browser's built-in XSS filter
# Adds X-XSS-Protection header
SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME-sniffing attacks
# Forces browser to respect declared content types
# Adds X-Content-Type-Options: nosniff header
SECURE_CONTENT_TYPE_NOSNIFF = True


# 3. Clickjacking Protection
# ---------------------------
# Prevents site from being embedded in iframes
# Protects against clickjacking attacks
# Options: 'DENY' (no iframes) or 'SAMEORIGIN' (same domain only)
X_FRAME_OPTIONS = 'DENY'


# 4. CSRF (Cross-Site Request Forgery) Protection
# ------------------------------------------------
# CSRF protection is enabled by default via CsrfViewMiddleware
# These settings provide additional security

# Prevent JavaScript access to CSRF cookie
# Reduces risk if XSS vulnerability exists
CSRF_COOKIE_HTTPONLY = True

# Use session storage for CSRF token (more secure than cookies)
# Set to True for maximum security
CSRF_USE_SESSIONS = False

# Prevent CSRF cookie from being sent in cross-site requests
# Options: 'Strict', 'Lax', or None
CSRF_COOKIE_SAMESITE = 'Strict'

# Additional CSRF trusted origins for production
# Add your production domains here
# CSRF_TRUSTED_ORIGINS = ['https://yourdomain.com']


# 5. Session Security
# -------------------
# Prevent JavaScript access to session cookie
# Reduces risk of session hijacking via XSS
SESSION_COOKIE_HTTPONLY = True

# Strict same-site policy for session cookies
# Prevents session cookies from being sent in cross-site requests
SESSION_COOKIE_SAMESITE = 'Strict'

# Session timeout (in seconds)
# Users logged out after 1 hour of inactivity
SESSION_COOKIE_AGE = 3600  # 1 hour

# Session cookies expire when browser closes
# More secure but less convenient
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Regenerate session key on login
# Prevents session fixation attacks
SESSION_SAVE_EVERY_REQUEST = False


# 6. Referrer Policy
# ------------------
# Controls how much referrer information is sent
# 'same-origin' only sends referrer for same-origin requests
SECURE_REFERRER_POLICY = 'same-origin'


# 7. Content Security Policy (CSP)
# ---------------------------------
# Note: For full CSP implementation, install django-csp package
# pip install django-csp
# Then add 'csp.middleware.CSPMiddleware' to MIDDLEWARE

# Uncomment these after installing django-csp:
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
# CSP_IMG_SRC = ("'self'", "data:", "https:")
# CSP_FONT_SRC = ("'self'",)
# CSP_CONNECT_SRC = ("'self'",)
# CSP_FRAME_ANCESTORS = ("'none'",)
# CSP_BASE_URI = ("'self'",)
# CSP_FORM_ACTION = ("'self'",)


# 8. Additional Security Headers
# -------------------------------
# These are automatically handled by SecurityMiddleware
# but can be customized if needed

# Proxy SSL Header (if behind a proxy like Nginx)
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# 9. Logging Configuration
# -------------------------
# Log security-related events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# =====================================================
# PRODUCTION vs DEVELOPMENT SETTINGS
# =====================================================

if DEBUG:
    # Development-specific settings
    print("=" * 60)
    print("⚠️  WARNING: Running in DEBUG mode!")
    print("⚠️  Some security features are disabled for development.")
    print("⚠️  NEVER use DEBUG=True in production!")
    print("=" * 60)
    
    # Allow any host in development
    ALLOWED_HOSTS = ['*']
else:
    # Production settings
    # Enable all security features
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Restrict allowed hosts to your domain
    ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
    
    # Add your production CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'https://yourdomain.com',
        'https://www.yourdomain.com',
    ]


# =====================================================
# SECURITY CHECKLIST FOR PRODUCTION DEPLOYMENT
# =====================================================
"""
Before deploying to production, ensure:

1. ✅ DEBUG = False
2. ✅ SECRET_KEY loaded from environment variable
3. ✅ ALLOWED_HOSTS set to specific domains
4. ✅ SECURE_SSL_REDIRECT = True
5. ✅ SESSION_COOKIE_SECURE = True
6. ✅ CSRF_COOKIE_SECURE = True
7. ✅ SECURE_HSTS_SECONDS = 31536000
8. ✅ Use HTTPS (get SSL certificate)
9. ✅ Configure proper database (not SQLite for production)
10. ✅ Set up proper static file serving
11. ✅ Configure email backend for error notifications
12. ✅ Regular security updates (pip install -U django)
13. ✅ Run: python manage.py check --deploy

Additional recommendations:
- Use environment variables for sensitive data
- Implement rate limiting for authentication
- Set up monitoring and alerting
- Regular security audits
- Keep dependencies updated
- Use a web application firewall (WAF)
"""