"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

SECURITY ENHANCEMENTS:
This settings file implements security best practices to protect against:
- Cross-Site Scripting (XSS)
- Cross-Site Request Forgery (CSRF)
- SQL Injection
- Clickjacking
- Man-in-the-Middle attacks
- Session hijacking

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Basic / Recommended: load secrets from env vars in production
# -----------------------------------------------------------------------------
# SECRET_KEY should be set as an environment variable in production.
# Example: export DJANGO_SECRET_KEY='your-production-secret'
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-f_k_i)d89r!95w$ow3hwfz$o#wk5j*%tcjve#jxa=ae*7_5$$_"
)

# Debug should be False in production. Use an environment variable to control it.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# In production, set this to your actual domain names (configured below when DEBUG=False)
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# -----------------------------------------------------------------------------
# Application definition
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'sslserver',

]

MIDDLEWARE = [
    # SecurityMiddleware must be as high as possible to apply security headers early
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Clickjacking protection (X-Frame-Options header)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Enforce minimum 8 characters for stronger passwords
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# Static & Media files
# -----------------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------------------------------------------------------
# Authentication redirect URLs
# -----------------------------------------------------------------------------
LOGIN_URL = '/relationship/login/'
LOGIN_REDIRECT_URL = '/relationship/books/'
LOGOUT_REDIRECT_URL = '/relationship/login/'

# -----------------------------------------------------------------------------
# Default primary key field type
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# -----------------------------------------------------------------------------
# ===================== SECURITY SETTINGS (ENFORCE HTTPS etc.) =================
# -----------------------------------------------------------------------------

# 1. HTTPS and SSL Settings
# NOTE: For local development keep SECURE_SSL_REDIRECT = False to avoid requiring TLS locally.
# In production (DEBUG=False) we enable the redirect below automatically.
SECURE_SSL_REDIRECT = False  # Will be turned on when DEBUG=False (see block below)

# HSTS (HTTP Strict Transport Security)
# Default to 0 for development. In production we enable long HSTS.
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# 2. Cookie Security
# These are False for development (no TLS). In production they will be set to True in the block below.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Prevent JavaScript from reading session cookie
SESSION_COOKIE_HTTPONLY = True

# CSRF cookie needs to be readable by client-side JS if you rely on JS frameworks reading it.
# Set CSRF_COOKIE_HTTPONLY = False so client-side code can read the CSRF token cookie if required.
CSRF_COOKIE_HTTPONLY = False

# SameSite policy: 'Lax' is a safe default that works with most auth flows.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Session lifetime and behavior
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = False

# 3. XSS / Content Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# 4. Clickjacking protection
X_FRAME_OPTIONS = 'DENY'  # or 'SAMEORIGIN' if you need framing from same origin

# 5. CSRF configuration
# Using cookies for CSRF (default). If using cross-domain requests, add your domains to CSRF_TRUSTED_ORIGINS below.
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'

# 6. Referrer Policy
SECURE_REFERRER_POLICY = 'same-origin'

# 7. Proxy (if behind a load balancer or reverse proxy)
# If you terminate SSL at a proxy (nginx, ELB), ensure the proxy sets X-Forwarded-Proto to 'https'.
# Then enable the line below in production so Django treats such requests as secure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# -----------------------------------------------------------------------------
# Logging (security-related)
# -----------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'security.log'),
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# -----------------------------------------------------------------------------
# Production overrides: when DEBUG is False we enable HTTPS and stricter cookie policies
# -----------------------------------------------------------------------------
if DEBUG:
    # Development-specific settings
    print("=" * 60)
    print("⚠️  WARNING: Running in DEBUG mode!")
    print("⚠️  Some security features are relaxed for development.")
    print("⚠️  NEVER use DEBUG=True in production!")
    print("=" * 60)

    # Keep ALLOWED_HOSTS limited in dev by default to avoid accidental exposure;
    # if you need to test with different hosts, modify ALLOWED_HOSTS locally.
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

else:
    # Production settings (applied when DEBUG==False)
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS (recommendation: set a long duration after testing)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Ensure cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Cookie policies
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # keep False so client-side can read CSRF token if needed

    # Restrict allowed hosts to your production domains
    ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "yourdomain.com,www.yourdomain.com").split(',')

    # CSRF trusted origins for secure cross-site requests (include scheme)
    CSRF_TRUSTED_ORIGINS = [
        'https://yourdomain.com',
        'https://www.yourdomain.com',
    ]

    # Optionally: log when starting in production
    print("Running with production security settings enabled.")

# -----------------------------------------------------------------------------
# CSP (Content Security Policy) - optional (requires django-csp)
# -----------------------------------------------------------------------------
# For stronger XSS protection consider enabling CSP via django-csp.
# pip install django-csp
# Then add 'csp.middleware.CSPMiddleware' to MIDDLEWARE and uncomment / tune these settings.
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
# CSP_IMG_SRC = ("'self'", "data:", "https:")
# CSP_FONT_SRC = ("'self'",)
# CSP_CONNECT_SRC = ("'self'",)
# CSP_FRAME_ANCESTORS = ("'none'",)

# -----------------------------------------------------------------------------
# Final notes and checklist (for your docs/README):
# - Set DJANGO_SECRET_KEY in environment for production.
# - Set DJANGO_DEBUG=False in production.
# - Set DJANGO_ALLOWED_HOSTS to comma-separated production hosts.
# - Configure a reverse proxy (nginx) to terminate TLS and set X-Forwarded-Proto header.
# - Obtain TLS certificates (Let's Encrypt / Certbot) and configure nginx to redirect HTTP->HTTPS.
# - Run `python manage.py check --deploy` before going live.
# -----------------------------------------------------------------------------
